### ISSUE TITLE
fortios_system_firmware_upgrade missing

### ISSUE THREAD

**Issue by daniel-afo** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#107]
Hello together,

we were using in the past the fortios_system_firmware_upgrade module, but it seems to be missing actually in the ansible version 2.10.x

The ansible documentation https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.10.html#known-issues suggest only to use the fully qualified collection names, but the module is missing under the list of fortinet.fortios modules https://docs.ansible.com/ansible/2.10/collections/fortinet/fortios/ 

Is there any plan for the new ansible release?

Best Regards

Dany

**Comment by JieX19** [comment]
Hi @daniel-afo,

Please install the latest version 2.0.2 to use the **upgrade.system.firmware** in **fortios_monitor** module. 

Here's the doc for fortios_monitor module https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_monitor.html, you can use upgrade.system.firmware in selector and provide all the required parameters in params to do the task. 

There have been huge changes for fortios collections since ansible 2.10, here's our new docs https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/index.html. Hope it helps.

Thanks!

**Comment by daniel-afo** [comment]
Dear @JieX19 ,

thanks for your response this clearifies it.

I copied now for that reason to not restructure it the old **fortios_system_firmware_upgrade module** module and renamed and reuse it. We were using it until now with the source "upload" but we would like to change it to fortiguard. 
Unfortunately is it not working as expected, i thought it relies on the filename, i tried many different like FGT_VM64_AZURE_v6.4.4.out, FGT_VM64_AZURE-v6-build1803-FORTINET.out, v6.4.4, 1803 but no sucess.

This is the debug output of one of these tries:
`fatal: [vdc01]: FAILED! => {
    "changed": true,
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "host": "10.254.254.2",
            "https": true,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ssl_verify": false,
            "system_firmware": {
                "file_content": null,
                "filename": "FGT_VM64_AZURE-v6-build1803-FORTINET.out",
                "format_partition": false,
                "source": "fortiguard"
            },
            "username": "dmin",
            "vdom": "root"
        }
    },
    "meta": {
        "action": "upgrade",
        "build": 1142,
        "http_method": "POST",
        "name": "firmware",
        "path": "system",
        "results": {
            "error": {
                "message": "download_failed"
            },
            "status": "error"
        },
        "serial": "FGVM01TM21002891",
        "status": "success",
        "vdom": "root",
        "version": "v6.2.5"
    }
}
`

If i trigger the download and upgrade directly from the fortigate gui is it working properly.

Any idea where it could rely?

Greetings Daniel

**Comment by JieX19** [comment]
Hi @daniel-afo,

I've reproduced the error. This is a special module we need to cover, I will update you once it's fixed.

Thanks!

**Comment by JieX19** [comment]
Hi @daniel-afo 

Please try the latest version 2.1.1 using comamnd:  **ansible-galaxy collection install fortinet.fortios:2.1.1**

Here's my working palybook:
```
tasks:
- name: Update Firmware
  fortios_monitor:
      vdom: "{{ vdom }}"
      selector: 'upgrade.system.firmware'
      params:
        source: "upload"
        filename: "FGT_VM64-v6-build1828-FORTINET.out"
        file_content: "{{ lookup( 'file', './FGT_VM64-v6-build1828-FORTINET.out') | string | b64encode }}"
```

Please note there would be a timeout error after the execution, because the device will restart when finishing the upgrading task. Please double check your device after upgrading the firmware. We are trying to find a good way to address it. 

Please let me know if you have any questions.

**Comment by Metzcall** [comment]
Hi!

@JieX19 Is there any fix/workaround for the timeout or another new module to perform this tasks?

**Comment by foxpatil** [comment]
@JieX19 is there any update on this upgrade module or any other module can be used for upgradinh firmware

**Comment by foxpatil** [comment]
@daniel-afo did you get the fix on this?

**Comment by foxpatil** [comment]
What will be the filename or file content if the file is on FTP server . please help

tasks:
- name: Update Firmware
  fortios_monitor:
      vdom: "{{ vdom }}"
      selector: 'upgrade.system.firmware'
      params:
        source: "upload"
        filename: 
        file_content:
