### ISSUE TITLE
Cannot remove all Administrative Access options from interface

### ISSUE THREAD

**Issue by winromulus** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#149]
Hi,

While using `fortios_system_interface`, passing an empty array for `allowaccess` does not clear the list of admin access options. I can't figure out a way to set that list to remove all options set on the interface. Is this a bug or am I doing something wrong?

**Comment by tethryus** [comment]
Same here

**Comment by jantari** [comment]
Just ran into this as well. When setting `allowaccess: []` that results in the same behavior as `allowaccess: omit` - the allowaccess setting on the firewall is not touched when it should be cleared.

This is probably related to #14

Nonetheless it is important to be able to set an empty allowaccess setting (unset allowaccess) for some interfaces. Not everyone wants all their interfaces to be pingable.

**Comment by JieX19** [comment]
Hi, @winromulus @jantari @tethryus 

Fortigate does not expose any restful API to unset an attribute currently. I will submit a request to the API team to see if we can support this feature in the future. 

Due to the request from the Redhat team, we cannot keep all the discussions in this thread. I will definitely follow up on this feature and update the doc once it's supported from the API end.

**Comment by jantari** [comment]
Hi @JieX19 do you know whether the API supports unsetting an attribute now? Thanks
