### ISSUE TITLE
Inconsistent use of lists/strings compared to fortiosapi

### ISSUE THREAD

**Issue by markodjukic** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#15]
There are some small but significant differences between how the Ansible modules handle data and how the fortiosapi handles data. These can be workaround in our code, but it creates a massive overhead both traversing dict structures to fix it, tracking all the exceptions and having to create the mappings back and forth between Ansible logic and fortiosapi logic in every scenario.

Some context, we're fetching the current running config for additional information about how the systems are configured to help drive decision about how to push new ansible configuration. However we are getting different results between what the fortiosapi returns and how we need to configure ansible.

Here's an example:
- System SNMP user call (/system.snmp/user) shows the attribute events as a string in the fortiosapi:
  "events": "cpu-high"
- The equivalent in the ansible modules takes the input as a list and then internally converts it to a string
https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/blob/master/plugins/modules/fortios_system_snmp_user.py#L358

Possible suggestions:
- Fix upstream in the api that it returns a list when queried through the get
- Accept both list and a string in the ansible module for consistency with the api, detect and deal with it in that L358 section
- Add methods to fetch data from the systems using ansible modules and then deal with the inconsistency issues internally

**Comment by chillancezen** [comment]
hi @markodjukic ,
Thanks for your great ideas in this issue.

- As far as I know, now FortiOS Ansible doesn't support a `GET` method to retrieve object infomation. 

- your are referring to `fortiosapi`,  do you mean calling `fortiosapi` with your own Python application, not FortiOS Ansible module in legacy `fortiosapi` way?

- our strategy is to deprecate legacy `fortiosapi` of FortiOS ansible in the future, the reason is the recent features or fixes have gone only into `httpapi`. We have the `notes` for each module in recent online document: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest.  So could you please migrate your playbook to `httpapi`, here is [one example](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/playbook.html) of `httpapi` .


I know what you are doing is retrieving current configuration of an object and doing comparison locally, then pushing new configuration to the device.  however, with Ansible model, the parameter `state: present/absent` defines a model of creating/updating and deleting an object. that's why in most cases you don't have to care much about what exactly the configuration of the object is, all you have to do is define the final object state in your object. 

- `Fix upstream in the api that it returns a list when queried through the get`:  I think this needs help and approval from Fortigate core engineering team, it may need longer cycle than fix in Ansible.

- `Accept both list and a string in the ansible module for consistency with the api, detect and deal with it in that L358 section` : this is impossible, Ansible parameters validation framework doesn't allow us to accept both list and a string at the same time.

- Handling above inconsistency is minor issue, whereas the major issue is what you pointed out, `Add methods to fetch data from the systems using ansible modules and then deal with the inconsistency issues internally`. Adding the 'GET' semantics method in FortiOS ansible modules can increase the flexibility thus you can manipulate the intermediate retrieved object. This can be a feature that I need to discuss with the team.  but @markodjukic could you please confirm whether current Ansible model: `state: present/absent` satisfies your requirement ?

Again thanks for your issue, Marko.
Link

**Comment by chillancezen** [comment]
just an update:  not like terraform, the ansible doesn't support full CURD(creat/update/retrieve/delete) model. specifically, `retrieve` semantics is not encouraged in Ansible if our module is going align more with community.

**Comment by chillancezen** [comment]
mark it closed.
please reopen in case of anything that we could help.
