### ISSUE TITLE
Issue on task with custom type

### ISSUE THREAD

**Issue by apellini** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#17]
I'm writing a role in ansible to configure multiple fortigate from Zero Day to Production and I have create first simple task to set NTP..

My Code:

`- name: Configure NTP Server
  fortios_system_ntp:
    host: '{{ ansible_host }}'
    username: '{{ fgt.user }}'
    password: '{{ ansible_password }}'
    ssl_verify: '{{ fgt.ssl_verify }}'
    https: '{{ fgt.https }}'
    system_ntp:
      ntpsync: "enable"
      server_mode: "enable"
      type: '{{ ntp.type }}'
      ntpserver:
        - id: '{{ item.id }}'
          server: '{{ item.server }}'
  loop: '{{ ntp.ntpserver }}'
  when: 'ansible_host in groups[item.site]'`

When I execute the play on this specific task it fails with a not useful error message:

`TASK [fortinet-onboard : Configure NTP Server] *********************************
failed: [host01-f22] (item={u'site': u'AAA', u'id': 1, u'server': u'2.2.2.1'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 1, "server": "2.2.2.1", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVIZRRPG_S45", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"}
failed: [host02-f22] (item={u'site': u'AAA', u'id': 1, u'server': u'2.2.2.1'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 1, "server": "2.2.2.1", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVKKSUP_SCA1", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"}
failed: [host01-f22] (item={u'site': u'AAA', u'id': 2, u'server': u'2.2.2.2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 2, "server": "2.2.2.2", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVIZRRPG_S45", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"}
failed: [host02-f22] (item={u'site': u'AAA', u'id': 2, u'server': u'2.2.2.2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 2, "server": "2.2.2.2", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVKKSUP_SCA1", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"}
`
This message "Error in repo" what means?

Could you help me please?

Regards,

Aldo Pellini

**Comment by chillancezen** [comment]
hi Aldo,
I see you are using loops, could you please share your complete playbooks with us in order to reproduce?

Thanks
Link

Sent from my iPhone

On Jun 13, 2020, at 6:24 AM, neope <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm writing a role in ansible to configure multiple fortigate from Zero Day to Production and I have create first simple task to set NTP..

My Code:

- name: Configure NTP Server fortios_system_ntp: host: '{{ ansible_host }}' username: '{{ fgt.user }}' password: '{{ ansible_password }}' ssl_verify: '{{ fgt.ssl_verify }}' https: '{{ fgt.https }}' system_ntp: ntpsync: "enable" server_mode: "enable" type: '{{ ntp.type }}' ntpserver: - id: '{{ item.id<http://item.id> }}' server: '{{ item.server }}' loop: '{{ ntp.ntpserver }}' when: 'ansible_host in groups[item.site<http://item.site>]'

When I execute the play on this specific task it fails with a not useful error message:

TASK [fortinet-onboard : Configure NTP Server] ********************************* failed: [host01-f22] (item={u'site': u'AAA', u'id': 1, u'server': u'2.2.2.1'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 1, "server": "2.2.2.1", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVIZRRPG_S45", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"} failed: [host02-f22] (item={u'site': u'AAA', u'id': 1, u'server': u'2.2.2.1'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 1, "server": "2.2.2.1", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVKKSUP_SCA1", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"} failed: [host01-f22] (item={u'site': u'AAA', u'id': 2, u'server': u'2.2.2.2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 2, "server": "2.2.2.2", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVIZRRPG_S45", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"} failed: [host02-f22] (item={u'site': u'AAA', u'id': 2, u'server': u'2.2.2.2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"id": 2, "server": "2.2.2.2", "site": "AAA"}, "meta": {"build": 335, "http_method": "POST", "http_status": 405, "name": "ntp", "path": "system", "serial": "FGVMEVKKSUP_SCA1", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"}
This message "Error in repo" what means?

Could you help me please?

Regards,

Aldo Pellini

**Comment by apellini** [comment]
I have solved with remove server_mode that require interface list filled.

Perhaps it is better to add some description in plus.

Thanks.

Aldo Pellini

Il giorno sab 13 giu 2020 alle ore 03:09 Jie (Link) Zheng <
notifications@github.com> ha scritto:

> hi Aldo,
> I see you are using loops, could you please share your complete playbooks
> with us in order to reproduce?
>
> Thanks
> Link
>
> Sent from my iPhone
>
> On Jun 13, 2020, at 6:24 AM, neope <notifications@github.com<mailto:

**Comment by chillancezen** [comment]
thanks Aldo, 

we generated these module using predefined schema.
we will do to improve the way to fill out those required fields.

I mark this issue closed now.
feel free to reopen and reach out to me for any FortiOS ansible issues.

thanks,
Link.
