### ISSUE TITLE
Bogus changed state in check mode

### ISSUE THREAD

**Issue by jplitza** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#235]
When I execute e.g. `fortios_system_interface` in check mode, it returns a changed state where there are none without check mode.

Turning on `-D` shows that the "before" part of the diff contains all possible keys, while the "after" only contains the keys I invoked the module with. (Also, almost everything is VALUE_SPECIFIED_IN_NO_LOG_PARAMETER, which makes the diff practically useless).

I guess this has to do with #193, although the proposed patch there explicitly only compares the given parameters.

**Comment by MaxxLiu22** [comment]
Hi @jplitza ,

The "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER" issue has been fixed in the latest fos 2.3.0 version, to upgrade you collection by using ``ansible-galaxy collection install fortinet.fortios:2.3.0``, I will go ahead to close this issue, if you still have question, feel free to reopen it or another case.

Thanks,
Maxx
