### ISSUE TITLE
fortios_extender_controller_dataplan module: different options have same name up to casing

### ISSUE THREAD

**Issue by felixfontein** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#325]
The fortios_extender_controller_dataplan module has several distinct options which are equal up to casing:

- option 'APN', option 'apn'
- option 'PDN', option 'pdn'

These options look very much like they should be *aliases* of each other, instead of distinct options.

I.e. `APN` should be an alias of `apn` (or vice versa), instead of having two separate options `APN` and `apn`. Or are these actually two options that can be set to different values independently from each other?

Ref: https://github.com/ansible/ansible/pull/83530

**Comment by MaxxLiu22** [comment]
Hi @felixfontein ,

Thank you for raising this issue. According to the Ansible documentation, "PDN" is used in FOS 6.4.0, while "pdn" is used in FOS 6.4.4 - 7.2.0. Ansible maintains both argument names to ensure compatibility with all versions of FOS. However, since 6.4.0 is quite outdated, I will consult the development team to see if we can remove the older argument name to avoid any confusing usage. or merge them to one argument.
![image](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/assets/98774290/f35b6a93-c082-470d-91aa-fb14ca145322)
Thanks,
Maxx

**Comment by felixfontein** [comment]
I would probably make the old name an alias of the new name, and forward the right name depending on the version to the device.

**Comment by MaxxLiu22** [comment]
Hi @felixfontein 

We have just released Ansible FOS 2.3.7, and the argument 'PDN' has been removed from our provider to prevent any confusion. You may upgrade to this version and give it a try at your convenience. Thank you.
```
ansible-galaxy collection install fortinet.fortios:2.3.7
```
Thanks,
Maxx
