### ISSUE TITLE
Multiple FortiOS versions 

### ISSUE THREAD

**Issue by tsirkin** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#84]
We have multiple clients with multiple FortiOS versions installed.  
We plan to run the ansible using ansible-runner/ansible-runner-service/AWX.  
But even using cli becomes cumbersome if we need multiple ansible installations.   
Since FortiOS collection version depends one the FG OS one and ansible support only one collection version per installation, how do you suggest handling this?  
We really need ansible to auto discover the version at runtime and use the right module.

**Comment by chillancezen** [comment]
hi @tsirkin  Tsirkin,

we have galaxy versions for FOS 6.0, 6.2, 6.4 now.

the majority of collection content are almost same, it means if you write a playbook for FOS 6.0, it's supposed to work on FOS 6.2 and 6.4. But it's not always the case, a few module has augmented parameters and the module itself is only available in FOS 6.2 or 6.4(because the API is introduced in later release).

the way we are going to solve multiversions is to unify content so that we don't distinguish internal FOS versions anymore in the future. 

Keep this issue open till release is ready

thanks,
Link

**Comment by tsirkin** [comment]
Thank you @chillancezen 
Do you have any timeline for this?

**Comment by chillancezen** [comment]
It will be no earlier than Feb 2021. I can give you a build to preview before then.

Sent from my iPhone

On Dec 22, 2020, at 3:49 PM, Tsirkin Evgeny <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you @chillancezen<https://github.com/chillancezen>
Do you have any timeline for this?

**Comment by tsirkin** [comment]
Sure,
preview would be very helpful.
Do you have a branch for it?

**Comment by chillancezen** [comment]
> Sure,
> preview would be very helpful.
> Do you have a branch for it?

hi @tsirkin ,

here is the unified collection to preview: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/releases/tag/unification

note this is not published to Galaxy. 

its doc: https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/index.html

**Comment by chillancezen** [comment]
hi @tsirkin, 
we've officially released to galaxy. 
please see latest document for unified versioning.

https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/index.html

mark `closed` now. please feel free to reopen. 
thanks.
