### ISSUE TITLE
Add the fortios_configuration_fact to the certified collections.

### ISSUE THREAD

**Issue by zaskan** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#86]
Is there any plan to add the fortios_configuration_fact module to the Red Hat's certified collections?

Thanks

**Comment by greenspartan** [comment]
Hello,
I was just about to create a post in order to ask the same thing ;).
Indeed, it would be very interesting to have fortios_configuration_fact module available in Certified Fortios collection (https://cloud.redhat.com/ansible/automation-hub/repo/published/fortinet/fortios/docs) so we can use it in Tower for instance.

Thanks !

Best Regards,

Adrien

**Comment by JieX19** [comment]
Hi @zaskan @greenspartan,

Thanks for your suggestion! We will definitely add fortios_configuration_fact to certified collection in our next release, and it's about early April. We'll update this ticket when it's released.

**Comment by chillancezen** [comment]
@zaskan @greenspartan , 
Included `2.0.1` in latest automation hub certified hub: https://cloud.redhat.com/ansible/automation-hub/repo/published/fortinet/fortios
